apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lablinuxtips
  name: lablinuxtips
spec:
  containers:
  - image: nginx
    name: lablinuxtips
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
